type: object

properties:
    name:
      type: string
      example: VEHICLE-REGISTRATION
    type:
      type: string
      enum:
        - Service
        - Application
      example: Service
    organization:
      type: object
      properties:
        name:
          type: string
          example: insurance-corporation-of-bc
    environments:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
            example: dev
          appId:
            type: string
            example: FDA8A444
          resourceLocator:
            type: string
            example: DEV.BUS.ICBC.VEHICLE-REGISTRATION
          spec:
            type: object
            properties:
              title:
                type: string
                example: Vehicle Registration
              version:
                type: string
                example: "1.0"
              summary:
                type: string
                example: This is a prototype API for the ICBC Vehicle Registration service. It is intended for testing and development purposes only.
              description:
                type: string
                example: Detailed explanation of the API for getting vehicle details.
              operations:
                type: array
                items:
                  type: object
                  properties:
                    operationId:
                      type: string
                      example: vehicle_list
                    method:
                      type: string
                      example: GET
                    path:
                      type: string
                      example: /v1/registration
                    summary:
                      type: string
                      example: Get a list of registered vehicles
                    scopes:
                      type: array
                      items:
                        type: string
                      example:
                        - user/VehicleOwnership.r
    gateway:
      type: object
      properties:
        id:
          type: string
          example: gw-bb86c
        displayName:
          type: string
          example: BB86C Gateway
        orgUnit:
          type: string
          example: digital-division
        permDataPlane:
          type: array
          items:
            type: string
          example:
            - sdx-ap
        permDomains:
          type: array
          items:
            type: string
          example:
            - sdx-pub-icbc-sap.api.gov.bc.ca
            - sdx.api.gov.bc.ca
