openapi: 3.1.1

info:
  title: SDX Member API
  version: "1.0"
  description:  |-
    # Introduction

    This is a prototype API for ADRs that support Connected Services.
    
    It is intended as a draft for helping with service design.

  license:
    name: Apache 2.0
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"

  contact:
    name: API Programme Services Team
    url: https://chat.developer.gov.bc.ca/channel/aps-ops

servers:
  - url: "/LAB.MIN.CITZ.SDX.MEMBER-API"
    description: Lab environment

tags:
  - name: Connections
    description: |-
      Connects represent consumers connecting to provider APIs.
  - name: Organizations
    description: |-
      Organizations represent a group or entity that offers products. They can have multiple organizational units and contacts.
  - name: Products
    description: |-
      Products are services or applications that are offered by an organization. They can have multiple environments.
  - name: Prototype
    description: |-
      Prototype APIs are used to test new ideas and concepts. They are not intended for production use and may change frequently.
      
paths:
  /v1/organizations:
    get:
      operationId: organizations_list

      summary: List All Organizations

      description: |
        To list all of the organizations available, send a GET request to /v1/organizations.

      tags:
        - Organizations

      responses:
        '200':        
          $ref: 'resources/organizations/responses/all_organizations.yml'

        '401':
          $ref: 'shared/responses/unauthorized.yml'

        '429':
          $ref: 'shared/responses/too_many_requests.yml'

        '500':
          $ref: 'shared/responses/server_error.yml'

        default:
          $ref: 'shared/responses/unexpected_error.yml'

      security: []

  /v1/products:
    get:
      operationId: products_list

      summary: List All Products

      description: |
        To list all of the products available, send a GET request to /v1/products.

      tags:
        - Products

      responses:
        '200':
          $ref: 'resources/products/responses/all_products.yml'

        '401':
          $ref: 'shared/responses/unauthorized.yml'

        '429':
          $ref: 'shared/responses/too_many_requests.yml'

        '500':
          $ref: 'shared/responses/server_error.yml'

        default:
          $ref: 'shared/responses/unexpected_error.yml'

      security: []

  /v1/connections:
    get:
      operationId: connections_list

      summary: List All Connections

      description: |
        To list all of the connections available, send a GET request to /v1/connections.

      tags:
        - Connections

      responses:
        '200':
          $ref: 'resources/connections/responses/all_connections.yml'

        '401':
          $ref: 'shared/responses/unauthorized.yml'

        '429':
          $ref: 'shared/responses/too_many_requests.yml'

        '500':
          $ref: 'shared/responses/server_error.yml'

        default:
          $ref: 'shared/responses/unexpected_error.yml'

      security: []

  # /v1/systems:
  #   get:
  #     operationId: systems_list

  #     summary: List All Systems

  #     description: |
  #       To list all of the systems available, send a GET request to /v1/systems.

  #     tags:
  #       - Prototype

  #     parameters:
  #       - $ref: 'resources/systems/parameters.yml#/type'
  #       - $ref: 'resources/systems/parameters.yml#/tag'
  #       - $ref: 'shared/parameters.yml#/per_page'
  #       - $ref: 'shared/parameters.yml#/page'

  #     responses:
  #       '200':
  #         $ref: 'resources/systems/responses/all_systems.yml'

  #       '401':
  #         $ref: 'shared/responses/unauthorized.yml'

  #       '429':
  #         $ref: 'shared/responses/too_many_requests.yml'

  #       '500':
  #         $ref: 'shared/responses/server_error.yml'

  #       default:
  #         $ref: 'shared/responses/unexpected_error.yml'

  #     security:
  #       - bearer_auth:
  #         - 'sdx-systems:read'

components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer

security:
  - bearer_auth: []
