openapi: 3.1.1

info:
  title: Toys
  version: "1.0"
  summary: |-
    This is a prototype API for the Toys service.
  description: |-
    Some info about toys would be good to have in a description about the service and its purpose.

  license:
    name: Apache 2.0
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"

  contact:
    name: API Programme Services Team
    url: https://chat.developer.gov.bc.ca/channel/aps-ops

servers:
  - url: "/"
    description: DEV environment

tags:
  - name: Toys
    description: |-
      All about Toys and what they provide to the world

paths:
  /v1/toys:
    summary: Get a list of toys
    get:
      tags:
        - Toys
      summary: Get a list of toys
      operationId: toysList
      security:
        - OAuth2:
            - "puki:Toys:read"

      description: |-
        This endpoint retrieves a list of toys for a user.
      responses:
        '200':
          description: Successful response returning toys
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: "PT001"
                    name:
                      type: string
                      example: "Squeaky Rubber Ball"
                    category:
                      type: string
                      example: "Interactive"
                    petType:
                      type: string
                      example: "Dog"
                    price:
                      type: number
                      format: float
                      example: 12.99
                    material:
                      type: string
                      example: "Natural Rubber"
                examples: [
                  {
                    "id": "PT001",
                    "name": "Squeaky Rubber Ball",
                    "category": "Interactive",
                    "petType": "Dog",
                    "price": 12.99,
                    "material": "Natural Rubber"
                  }
                ]

        '401':
          $ref: 'shared/responses/unauthorized.yml'

        '404':
          $ref: 'shared/responses/not_found.yml'

        '500':
          $ref: 'shared/responses/server_error.yml'

        default:
          $ref: 'shared/responses/unexpected_error.yml'

components:
  securitySchemes:
    OAuth2:
      type: oauth2
      description: |-
        OpenID Connect authentication is used to secure the API. Clients must obtain an access token from the OpenID Connect provider and include it in the Authorization header of their requests.
      flows:
        authorizationCode:
          authorizationUrl: https://auth.developer.gov.bc.ca/authorize
          tokenUrl: https://auth.developer.gov.bc.ca/token
          scopes:
            "puki:Toys:read": Read information about a user's Toys
            "puki:Toys:admin": Administer user's Toys
