openapi: 3.1.0
# info-description
info:
  # no-eval-in-markdown
  # no-script-tags-in-markdown
  title: Example API with wellformdness violations <script>alert("You are Hacked");</script> eval(
  version: 1.0.0

# openapi-tags-alphabetical
tags:
  - name: "Badger"
  - name: "Aardvark"
  - name: "Moose"
  # openapi-tags-uniqueness
  - name: "Moose"

paths:
  /users:
    # operation-description
    get:
      operationId: get-users
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

    post:
      operationId: create-user
      description: Create a User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      # operation-success-response This is only triggered if there is at lease on response defined, hence the 418
      responses:
        "418":
          description: teapot

  # path-keys-no-trailing-slash
  /users/{id}/:
    get:
      operationId: get-user
      description: Get a User by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    # operation-operationId
    delete:
      description: Delete a User
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '201':
          description: User has been successfully deleted.

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        created:
          anyOf:
            - type: string
              format: date-time
            - type: integer
        status:
          type: string
          enum:
            - ACTIVE
            - INACTIVE
        roles:
          type: array
      required:
        - id
        - status

    CreateUserRequest:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          enum:
            - ACTIVE
            - INACTIVE