openapi: 3.1.1

info:
  title: <Service Name>
  version: "1.0"
  description: |-
    Description about the service and its purpose.

  license:
    name: Apache 2.0
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"

  contact:
    name: API Programme Services Team
    url: https://chat.developer.gov.bc.ca/channel/aps-ops

servers:
  - url: "/LAB/[MemberClass]/[MemberCode]/[Service]"
    description: Lab environment

tags:
  - name: Prototype
    description: |-
      Prototype APIs are used to test new ideas and concepts. They are not intended for production use and may change frequently.

paths:
  /v1/[resourcetype]:
    get:
      tags:
        - Prototype
      summary: Get a resource
      operationId: resourcetype_list
      security:
        - bearer_auth:
          - '[resourcetype]:read'

      description: |-
        This endpoint retrieves a resource.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: string
                    example: "Resource data"

        '401':
          $ref: 'shared/responses/unauthorized.yml'

        '404':
          $ref: 'shared/responses/not_found.yml'

        '500':
          $ref: 'shared/responses/server_error.yml'

        default:
          $ref: 'shared/responses/unexpected_error.yml'

components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer